name: my_card_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  purchases_flutter: ^7.0.0
  flutter_launcher_icons: ^0.14.4

  # Firebase関連
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # ユーティリティ
  intl: ^0.20.2
  share_plus: ^10.0.0

  # 画像・ファイル処理
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.2
  image_picker: ^1.1.0
  image_cropper: ^7.0.0

  # 暗号化・認証
  crypto: ^3.0.3
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"
