// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPevQLvMAI51kqadEqHww2AKqb2Rh-z6Y',
    appId: '1:341979016348:web:0cb300d00456539c525159',
    messagingSenderId: '341979016348',
    projectId: 'shelinekko',
    authDomain: 'shelinekko.firebaseapp.com',
    storageBucket: 'shelinekko.firebasestorage.app',
    measurementId: 'G-F6MLX3REP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIDaY3eE1q60ylOXA64XXLFvMvSrCf450',
    appId: '1:341979016348:android:0fb18b6443b1ecbe525159',
    messagingSenderId: '341979016348',
    projectId: 'shelinekko',
    storageBucket: 'shelinekko.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIqK4A2ZZ9_TjpanWwzxDuhcKNFfe6aC4',
    appId: '1:341979016348:ios:69cd3fded55c9552525159',
    messagingSenderId: '341979016348',
    projectId: 'shelinekko',
    storageBucket: 'shelinekko.firebasestorage.app',
    iosBundleId: 'com.example.myCardApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIqK4A2ZZ9_TjpanWwzxDuhcKNFfe6aC4',
    appId: '1:341979016348:ios:69cd3fded55c9552525159',
    messagingSenderId: '341979016348',
    projectId: 'shelinekko',
    storageBucket: 'shelinekko.firebasestorage.app',
    iosBundleId: 'com.example.myCardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPevQLvMAI51kqadEqHww2AKqb2Rh-z6Y',
    appId: '1:341979016348:web:bea99b5e7ffcfce7525159',
    messagingSenderId: '341979016348',
    projectId: 'shelinekko',
    authDomain: 'shelinekko.firebaseapp.com',
    storageBucket: 'shelinekko.firebasestorage.app',
    measurementId: 'G-98V9TDMH74',
  );
}
